{% set name = "mkdocs-autorefs" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-autorefs-{{ version }}.tar.gz
  sha256: b8156d653ed91356e71675ce1fa1186d2b2c2085050012522895c9aa98fca3e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - markdown >=3.3,<4.0
    - mkdocs >=1.1,<2.0
    - python >=3.6,<4.0

test:
  imports:
    - mkdocs_autorefs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/autorefs
  summary: Automatically link across pages in MkDocs.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
